# tasks file
---
- name: first-run | check
  ansible.builtin.shell: >
    dpkg-query -W -f='${Status}' mariadb-server | grep -q 'install ok installed'
  register: mysqld_installed
  changed_when: false
  failed_when: false
  tags:
    - mariadb-server-first-run-check
