# tasks file
---
- name: ib logfile | get datadir
  mysql_variables:
    variable: datadir
  register: datadir_value
  tags:
    - mariadb-server-store-datadir
    - mariadb-server-store-datadir-retrieve

# Needed because of Ansible 1 / 2 differences
- name: ib logfile | store datadir
  set_fact:
     mariadb_server_datadir: "{{ datadir_value.msg.0.1 if datadir_value.msg.0.1 is defined else datadir_value.msg }}"
  tags:
    - mariadb-server-store-datadir
    - mariadb-server-store-datadir-set-fact

- name: ib logfile | stop service
  service:
    name: mysql
    state: stopped
  when: mysqld_installed.rc != 0
  tags:
    - mariadb-server-ib-logfile-stop-service

- name: ib logfile | remove ib_logfile(s)
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ mariadb_server_datadir.rstrip('/') }}/ib_logfile0"
    - "{{ mariadb_server_datadir.rstrip('/') }}/ib_logfile1"
  when: mysqld_installed.rc != 0
  tags:
    - mariadb-server-ib-logfile-remove

- name: ib logfile | start service
  service:
    name: mysql
    state: started
  when: mysqld_installed.rc != 0
  tags:
    - mariadb-server-ib-logfile-start-service
