# tasks file
---
- name: install | configure debconf
  ansible.builtin.debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ mariadb_server_debconf_selections }}"
  changed_when: false
  tags:
    - mariadb-server-install-configure-debconf

- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ mariadb_server_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - mariadb-server-install-dependencies

- name: install | dependencies | check service
  ansible.builtin.service:
    name: mysql
    state: started
  tags:
    - mariadb-server-install-dependencies
    - mariadb-server-install-dependencies-check

- name: install | additional
  ansible.builtin.apt:
    name: "{{ mariadb_server_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - mariadb-server-install-additional
