# tasks file
---
- name: first run
  ansible.builtin.import_tasks: first-run.yml
  tags:
    - configuration
    - mariadb-server
    - mariadb-server-first-run

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - mariadb-server
    - mariadb-server-install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - mariadb-server
    - mariadb-server-configure

#- name: toolkit udfs
#  ansible.builtin.import_tasks: toolkit-udfs.yml
#  tags:
#    - configuration
#    - mariadb-server
#    - mariadb-server-toolkit-udfs
#
#- name: zoneinfo
#  ansible.builtin.import_tasks: zoneinfo.yml
#  tags:
#    - configuration
#    - mariadb-server
#    - mariadb-server-zoneinfo
#  when: mariadb_server_zoneinfo_manage | bool
#
#- name: databases
#  ansible.builtin.import_tasks: databases.yml
#  tags:
#    - configuration
#    - mariadb-server
#    - mariadb-server-databases
#
#- name: users
#  ansible.builtin.import_tasks: users.yml
#  tags:
#    - configuration
#    - mariadb-server
#    - mariadb-server-users
#
#- name: plugins
#  ansible.builtin.import_tasks: plugins.yml
#  tags:
#    - configuration
#    - mariadb-server
#    - mariadb-server-plugins
#
#- name: queries
#  ansible.builtin.import_tasks: queries.yml
#  tags:
#    - configuration
#    - mariadb-server
#    - mariadb-server-queries
#
#- name: ib-logfile
#  ansible.builtin.import_tasks: ib-logfile.yml
#  tags:
#    - configuration
#    - mariadb-server
#    - mariadb-server-ib-logfile

- name: start and enable service
  ansible.builtin.service:
    name: mysql
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - mariadb-server-start-enable-service
