# tasks file
---
- name: plugins | create (lock) directory
  file:
    path: "{{ mariadb_server_lock_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - mariadb-server-plugins-lock-directory

- name: plugins | uninstall
  shell: >
    mysql -e "UNINSTALL PLUGIN {{ item.name }};" && rm {{ mariadb_server_lock_path }}/{{ item.name | lower }}
  args:
    removes: "{{ mariadb_server_lock_path }}/{{ item.name | lower }}"
  with_items: "{{ mariadb_server_plugins_absent }}"
  tags:
    - mariadb-server-plugins-uninstall

- name: plugins | install
  shell: >
    mysql -e "INSTALL PLUGIN {{ item.name }} SONAME '{{ item.soname }}';" && touch {{ mariadb_server_lock_path }}/{{ item.name | lower }}
  args:
    creates: "{{ mariadb_server_lock_path }}/{{ item.name | lower }}"
  with_items: "{{ mariadb_server_plugins_present }}"
  tags:
    - mariadb-server-plugins-install
